### ISSUE TITLE
DBW: Tuning of DBW node PID

### ISSUE THREAD

**Issue by Deborah-Digges** [tokyo-drift/todos#21]
We can also consider using MPC

**Comment by zerepolbap** [comment]
We may also tune linear PID, to reduce throttle/brake cycles.

**Comment by zerepolbap** [comment]
Note from the specs:
> As in the Path Planning project, acceleration should not exceed 10 m/s^2 and jerk should not exceed 10 m/s^3

**Comment by zerepolbap** [comment]
Also from the project description:
> Note that throttle values passed to publish should be in the range 0 to 1. Brake values passed to publish should be in units of torque (N*m). The correct values for brake can be computed using the desired acceleration, weight of the vehicle, and wheel radius.

**Comment by zerepolbap** [comment]
In my view, as of today, steering is quite OK. Acceleration/braking works OK too. Some suggestions for "improvement":

In `twist_controller.py`:

- Max acceleration is currently set to `mx=0.5 * accel_limit`. It could be set to `mx=accel_limit`and it would still be within the 10 m/s^2 allowed margin.
- Braking is set to `1000*abs(throttle)`. To actually have a torque value, it could be changed to `wheel_radius * car_weight * acceleration` provided that `acceleration` can be approximated by `abs(throttle)`.

But I have tried this approach and the result was worst that what we have today, so it'll probably require some more tuning. Or just leaving as it is :-)

**Comment by Deborah-Digges** [comment]
- Removed the hard coded value and compute torque from vehicle_mass: https://github.com/tokyo-drift/capstone-project/pull/20/files
