### ISSUE TITLE
Waypoint updater: Possible optimization of search

### ISSUE THREAD

**Issue by Deborah-Digges** [tokyo-drift/todos#22]

**Comment by Deborah-Digges** [comment]
- There’s a node in ros called `waypoint_updater` that reads points from the rostopic `/base_waypoints`. Based on the car’s current pose, the node publishes 200 points(configurable) which are ahead to the car to `final_waypoints` which represents the future trajectory of the car


- the code for it is here: https://github.com/tokyo-drift/capstone-project/blob/master/ros/src/waypoint_updater/waypoint_updater.py


- Specfically, the `update_and_publish` method


- This is the section of code that finds the `next_waypoint` based on the current pose of the car: https://github.com/tokyo-drift/capstone-project/blob/master/ros/src/waypoint_updater/waypoint_updater.py#L86-L125

- We want to see if there is a way to optimize this method

**Comment by Deborah-Digges** [comment]
Deferring this task as @zerepolbap has confirmed that the current implementation is already quite good

**Comment by ChrisShepherd81** [comment]
According to the last commetn I close this issue.
