### ISSUE TITLE
Limit speed to 10 mph

### ISSUE THREAD

**Issue by zerepolbap** [tokyo-drift/todos#25]

**Comment by oxidase** [comment]
Captured from slack 
> speed limit is set at `./waypoint_loader/launch/waypoint_loader.launch`. There's another file named `./waypoint_loader/launch/waypoint_loader_site.launch` which apparently is the one needed to run in Carla. PID adapts to 10mph correctly (well... waypoint_loader seems to assume speed in node config is km/h and not mph, so I had to put "16" as value).
* 40 kmh in simulation mode https://github.com/tokyo-drift/capstone-project/blob/18a7a30469e957a1bb6b1ff87d3f6281fab99472/ros/src/waypoint_loader/launch/waypoint_loader.launch#L5
* 10 kmh in with the car DBW https://github.com/tokyo-drift/capstone-project/blob/18a7a30469e957a1bb6b1ff87d3f6281fab99472/ros/src/waypoint_loader/launch/waypoint_loader_site.launch#L5

Probably we could change 10 to 16, but for a "remote" test drive slower is better

**Comment by zerepolbap** [comment]
They have changed the requirement to: 
>  **Speed Limit**: Be sure to respect the speed limit set by the `velocity` param (km/h) in waypoint_loader

This was already done in our code, so I believe there is nothing else to do here.
